export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const SEARCH_SUCCEEDED = 'SEARCH_SUCCEEDED';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const ITEM_ACTIVATED = 'ITEM_ACTIVATED';
export const ITEM_SELECTED = 'ITEM_SELECTED';
export const DISPOSE_SEARCH_RESULTS = 'DISPOSE_SEARCH_RESULTS';
