export const FETCH_VENUES = 'FETCH_VENUES';
export const REQUEST_VENUES = 'REQUEST_VENUES';
export const RECEIVE_VENUES = 'RECEIVE_VENUES';
export const REQUEST_TIPS = 'REQUEST_TIPS';
export const RECEIVE_TIPS = 'RECEIVE_TIPS';
